# Generated by Django 5.0.1 on 2024-01-05 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 15, 1, 55, 154741, tzinfo=datetime.timezone.utc)),
        ),
    ]
