# Generated by Django 5.0.1 on 2024-01-05 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_player_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
