# Generated by Django 5.0.1 on 2024-01-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='THPK4NR76XOMAFLJ46BO4FV57E3H5O7V', max_length=100),
        ),
    ]
