# Generated by Django 5.0.1 on 2024-01-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0004_player_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='RZBO6E5KJGFLLHSP3U75IYGZ3ZNB3NBR', max_length=100),
        ),
    ]
