# Generated by Django 5.0.2 on 2024-02-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0006_matchhistory_alter_player_totp_secret_gamesession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='SNVQVHYVHNLDSLJLG3Z6Z62KQK6LRUXP', max_length=100),
        ),
    ]
