# Generated by Django 5.0.1 on 2024-02-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0006_matchhistory_alter_player_totp_secret_gamesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='VGHIWSA2KCENXGRZS5UGOFYTBD5S5WTT', max_length=100),
        ),
    ]
