# Generated by Django 5.0.1 on 2024-01-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0006_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='5LLHMTV7YADZ2F6UKUYW4NKTM4VLIXAD', max_length=100),
        ),
    ]
