# Generated by Django 5.0.1 on 2024-01-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0007_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='QXPHTQGUY5ADQLPJMMEHO32ILHR2EYJY', max_length=100),
        ),
    ]
