# Generated by Django 5.0.1 on 2024-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0007_player_is_logged_in_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='RDKNDSYPMI4A23J5AULPWYOI7LGUPK4L', max_length=100),
        ),
    ]
