# Generated by Django 5.0.2 on 2024-02-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0007_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='I3U4PFZ5RIJ2HO2DSXSUG6T2WS7OBCBA', max_length=100),
        ),
    ]
