# Generated by Django 5.0.1 on 2024-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0007_player_is_logged_in_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='player2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='7FOWO4EZEQLBNXVHNWJP264H6LTFFTHG', max_length=100),
        ),
    ]
