# Generated by Django 5.0.2 on 2024-02-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0008_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='T5T3XCBANOB44DICF4HHAHNAMSQVU6XX', max_length=100),
        ),
    ]
