# Generated by Django 5.0.1 on 2024-02-19 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0009_remove_playerqueue_player_alter_player_totp_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.CharField(default='System', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='MNEOVKNNM3OE4NC5Y622HPSCHOLB64VM', max_length=100),
        ),
    ]
