# Generated by Django 5.0.2 on 2024-02-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0009_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='3LTBS32L77LPMTSVAB6KVEZTORRQVRNP', max_length=100),
        ),
    ]
