# Generated by Django 5.0.2 on 2024-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0010_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='BKYBPECVEZWQYCNSTVZVP3D4A6UWA2H3', max_length=100),
        ),
    ]
