# Generated by Django 5.0.1 on 2024-02-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0010_notification_is_system_generated_tournament_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='2WBWPW2MD56GTGJI3P5CXXXAMZOYRQLF', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('finals', 'Finals')], default='pending', max_length=12),
        ),
    ]
