# Generated by Django 5.0.1 on 2024-02-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0011_alter_player_totp_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', null=True, upload_to='./'),
        ),
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='QGYU6TZNMLJS7ALX3E4BTC5T5OWBLJID', max_length=100),
        ),
    ]
