# Generated by Django 5.0.2 on 2024-02-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0012_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='TIRMZ7PMBN6ORGEE6P5HM5YH6BSQFRGM', max_length=100),
        ),
    ]
