# Generated by Django 5.0.1 on 2024-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0012_alter_player_profile_avatar_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='./default_avatar.jpg', null=True, upload_to='./'),
        ),
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='FJF6POSBRWWJVJWP3NT44VAST3IB3APV', max_length=100),
        ),
    ]
