# Generated by Django 5.0.2 on 2024-02-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0016_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.CharField(default='System', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='ZKPQ5HXXLZNIX3WBIBFVEB2YRAJO2Z3I', max_length=100),
        ),
    ]
