# Generated by Django 5.0.2 on 2024-02-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_accounts', '0017_tournament_creator_alter_player_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(default='2BJOX72RZGOUBE4EYVEOUD3TKYE4HYTD', max_length=100),
        ),
    ]
